title: Ben
description: My Personal Blog
author: 应佳辉
logo: /ben-ying.github.io/static/img/avatar.png
github: https://github.com/ben-ying
about: Android开发工程师

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
